[package]
name = "trezor_lib"
version = "0.1.0"
authors = ["SatoshiLabs <info@satoshilabs.com>"]
edition = "2018"
resolver = "2"
build = "build.rs"

[features]
bitcoin_only = []
test = ["cc", "glob"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
split-debuginfo = "unpacked"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
cty = "0.2.1"
pasta_curves = { git = "https://github.com/jarys/pasta_curves.git", branch = "no-std-hashtocurve", default-features = false }
sinsemilla_trezor = { git = "https://github.com/jarys/sinsemilla_trezor.git", default_features = false}

[dependencies.cstr_core]
version = "0.2.2"
default_features = false

[build-dependencies.bindgen]
version = "0.58.0"
default_features = false
features = ["runtime"]

[build-dependencies.cc]
optional = true
version = "1.0.68"

[build-dependencies.glob]
optional = true
version = "0.3.0"
