[package]
name = "trezor_lib"
version = "0.1.0"
authors = ["SatoshiLabs <info@satoshilabs.com>"]
edition = "2021"
build = "build.rs"

[features]
default = ["model_tt"]
bitcoin_only = []
model_tt = []
model_t1 = []
ui = []
ui_debug = []
test = ["cc", "glob"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
split-debuginfo = "unpacked"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
bech32 = { version = "0.8.1", default_features = false }
group = { version = "0.11", default-features = false }
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default_features = false }
rand_chacha = { version = "0.3.1", default-features = false }
#pasta_curves = {version = "0.3", default-features = false, features = ["alloc"] } # { git = "https://github.com/jarys/pasta_curves.git", branch="alloc", default-features = false, features = ["bits"] }
pasta_curves = { path="/home/agi/code/pasta_curves", default-features = false, features = ["unboxed_closures"] }

[dependencies.orchard]
path = "/home/agi/code/orchard"
#git = "https://github.com/jarys/orchard"
#branch = "no-std-alloc"
default-features = false
features = []

#[dependencies.pasta_curves]
#git = "https://github.com/zcash/pasta_curves"
#rev = "738fb60796d39b33f5b0a0337b8fabfcc81f98e1"
#default-features = false
#features = ["alloc"]

[dependencies.f4jumble]
git = "https://github.com/zcash/librustzcash"
rev = "6e39480c589bcb1b548c507aa96575368e72952a"
default-features = false

[profile.test]
split-debuginfo = "unpacked"

# Runtime dependencies

[dependencies.cty]
version = "0.2.1"

[dependencies.heapless]
version = "0.7.3"
default_features = false

[dependencies.cstr_core]
version = "0.2.4"
default_features = false

# Build dependencies

[build-dependencies.bindgen]
version = "0.59.1"
default_features = false
features = ["runtime"]

# Build dependencies used for linking the test binary

[build-dependencies.cc]
optional = true
version = "1.0.69"

[build-dependencies.glob]
optional = true
version = "0.3.0"
